// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class Choice
    {
        [Required]
        [Column("choiceBody")]
        [StringLength(100)]
        public string ChoiceBody { get; set; }
        [Key]
        [Column("choiceID")]
        public int ChoiceId { get; set; }
        [Key]
        [Column("questionID")]
        public int QuestionId { get; set; }

        [ForeignKey(nameof(QuestionId))]
        [InverseProperty("Choice")]
        public virtual Question Question { get; set; }
    }
}