// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class Choice
    {
        public string choiceBody { get; set; }
        public int choiceID { get; set; }
        public int questionID { get; set; }

        public virtual Question question { get; set; }
    }
}