// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class Course
    {
        public Course()
        {
            DepartmentCourse = new HashSet<DepartmentCourse>();
            Exam = new HashSet<Exam>();
            InstructorCourse = new HashSet<InstructorCourse>();
            Question = new HashSet<Question>();
            StudentCourse = new HashSet<StudentCourse>();
            Topic = new HashSet<Topic>();
        }

        [Key]
        [Column("courseID")]
        public int CourseId { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("duration")]
        public int Duration { get; set; }
        [Column("courseGrade")]
        public int CourseGrade { get; set; }
        [Column("NMCQ")]
        public int? Nmcq { get; set; }
        [Column("NTF")]
        public int? Ntf { get; set; }

        [InverseProperty("Course")]
        public virtual ICollection<DepartmentCourse> DepartmentCourse { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<Exam> Exam { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<InstructorCourse> InstructorCourse { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<Question> Question { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<StudentCourse> StudentCourse { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<Topic> Topic { get; set; }
    }
}