// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class Department
    {
        public Department()
        {
            DepartmentCourses = new HashSet<DepartmentCourse>();
            Instructors = new HashSet<Instructor>();
            Students = new HashSet<Student>();
        }

        public int deptID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public int? managerID { get; set; }

        public virtual Instructor manager { get; set; }
        public virtual ICollection<DepartmentCourse> DepartmentCourses { get; set; }
        public virtual ICollection<Instructor> Instructors { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}