// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class Department
    {
        public Department()
        {
            DepartmentCourse = new HashSet<DepartmentCourse>();
            Instructor = new HashSet<Instructor>();
            Student = new HashSet<Student>();
        }

        [Key]
        [Column("deptID")]
        public int DeptId { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [Column("description")]
        [StringLength(100)]
        public string Description { get; set; }
        [Required]
        [Column("location")]
        [StringLength(100)]
        public string Location { get; set; }
        [Column("managerID")]
        public int? ManagerId { get; set; }

        [ForeignKey(nameof(ManagerId))]
        [InverseProperty("Department")]
        public virtual Instructor Manager { get; set; }
        [InverseProperty("Dept")]
        public virtual ICollection<DepartmentCourse> DepartmentCourse { get; set; }
        [InverseProperty("Dept")]
        public virtual ICollection<Instructor> Instructor { get; set; }
        [InverseProperty("Dept")]
        public virtual ICollection<Student> Student { get; set; }
    }
}