// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class DepartmentCourse
    {
        [Key]
        [Column("deptID")]
        public int DeptId { get; set; }
        [Key]
        [Column("courseID")]
        public int CourseId { get; set; }

        [ForeignKey(nameof(CourseId))]
        [InverseProperty("DepartmentCourse")]
        public virtual Course Course { get; set; }
        [ForeignKey(nameof(DeptId))]
        [InverseProperty(nameof(Department.DepartmentCourse))]
        public virtual Department Dept { get; set; }
    }
}