// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamSystem.Entities
{
    public partial class ExamAnswersResult
    {
        public int id { get; set; }
        public string Ans { get; set; }
        public string Que { get; set; }
    }
}
