// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class Exam
    {
        public Exam()
        {
            StudentAnswers = new HashSet<StudentAnswers>();
        }

        [Key]
        [Column("examID")]
        public int ExamId { get; set; }
        [Column("courseID")]
        public int? CourseId { get; set; }

        [ForeignKey(nameof(CourseId))]
        [InverseProperty("Exam")]
        public virtual Course Course { get; set; }
        [InverseProperty("Exam")]
        public virtual ICollection<StudentAnswers> StudentAnswers { get; set; }
    }
}