// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class InstructorCourse
    {
        [Key]
        [Column("InsID")]
        public int InsId { get; set; }
        [Key]
        [Column("courseID")]
        public int CourseId { get; set; }

        [ForeignKey(nameof(CourseId))]
        [InverseProperty("InstructorCourse")]
        public virtual Course Course { get; set; }
        [ForeignKey(nameof(InsId))]
        [InverseProperty(nameof(Instructor.InstructorCourse))]
        public virtual Instructor Ins { get; set; }
    }
}