// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class Instructor
    {
        public Instructor()
        {
            Departments = new HashSet<Department>();
            InstructorCourses = new HashSet<InstructorCourse>();
        }

        public int InsID { get; set; }
        public string name { get; set; }
        public string degree { get; set; }
        public double salary { get; set; }
        public int? userID { get; set; }
        public int? deptID { get; set; }

        public virtual Department dept { get; set; }
        public virtual User user { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<InstructorCourse> InstructorCourses { get; set; }
    }
}