// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class Question
    {
        public Question()
        {
            Choice = new HashSet<Choice>();
        }

        [Key]
        [Column("questionID")]
        public int QuestionId { get; set; }
        [Required]
        [Column("body")]
        [StringLength(500)]
        public string Body { get; set; }
        [Column("modelAnswer")]
        public int ModelAnswer { get; set; }
        [Column("grade")]
        public int Grade { get; set; }
        [Column("type")]
        public int Type { get; set; }
        [Column("courseID")]
        public int? CourseId { get; set; }

        [ForeignKey(nameof(CourseId))]
        [InverseProperty("Question")]
        public virtual Course Course { get; set; }
        [InverseProperty("Question")]
        public virtual ICollection<Choice> Choice { get; set; }
    }
}