// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamSystem.Entities
{
    public partial class reportExamQuestionsResult
    {
        public int? qno { get; set; }
        public string cno { get; set; }
        public string qbody { get; set; }
    }
}
