// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class Repo
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        public string QuestionBody { get; set; }
        [StringLength(100)]
        public string ModelAnswer { get; set; }
        [StringLength(100)]
        public string StudentAnswer { get; set; }
        [StringLength(100)]
        public string Correct { get; set; }
    }
}