// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamSystem.Entities
{
    public partial class selectStudCouseResult
    {
        public int grade { get; set; }
        public string status { get; set; }
        public int studentID { get; set; }
        public int courseID { get; set; }
    }
}
