// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamSystem.Entities
{
    public partial class selectStudentCourseResult
    {
        public int courseID { get; set; }
        public string name { get; set; }
        public int duration { get; set; }
        public int courseGrade { get; set; }
        public int? NMCQ { get; set; }
        public int? NTF { get; set; }
    }
}
