// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamSystem.Entities
{
    public partial class selectStudentAnswerResult
    {
        public int studentID { get; set; }
        public int questionID { get; set; }
        public int examID { get; set; }
        public int? studentAnswer { get; set; }
    }
}
