// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamSystem.Entities
{
    public partial class SelectInstructor_ActionResult
    {
        public int InsID { get; set; }
        public string name { get; set; }
        public string degree { get; set; }
        public double salary { get; set; }
        public int? userID { get; set; }
        public int? deptID { get; set; }
    }
}
