// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class Student
    {
        public Student()
        {
            StudentAnswers = new HashSet<StudentAnswer>();
            StudentCourses = new HashSet<StudentCourse>();
        }

        public int studentID { get; set; }
        public string name { get; set; }
        public int age { get; set; }
        public string address { get; set; }
        public int? deptID { get; set; }
        public int? userID { get; set; }

        public virtual Department dept { get; set; }
        public virtual User user { get; set; }
        public virtual ICollection<StudentAnswer> StudentAnswers { get; set; }
        public virtual ICollection<StudentCourse> StudentCourses { get; set; }
    }
}