// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class StudentCourse
    {
        [Column("grade")]
        public int? Grade { get; set; }
        [Required]
        [Column("status")]
        
        public int? Status { get; set; }
        [Key]
        [Column("studentID")]
        public int StudentId { get; set; }
        [Key]
        [Column("courseID")]
        public int CourseId { get; set; }

        [ForeignKey(nameof(CourseId))]
        [InverseProperty("StudentCourse")]
        public virtual Course Course { get; set; }
        [ForeignKey(nameof(StudentId))]
        [InverseProperty("StudentCourse")]
        public virtual Student Student { get; set; }
    }
}