// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class StudentCourse
    {
        public int grade { get; set; }
        public string status { get; set; }
        public int studentID { get; set; }
        public int courseID { get; set; }

        public virtual Course course { get; set; }
        public virtual Student student { get; set; }
    }
}