// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class Student
    {
        public Student()
        {
            StudentAnswers = new HashSet<StudentAnswers>();
            StudentCourse = new HashSet<StudentCourse>();
        }

        [Key]
        [Column("studentID")]
        public int StudentId { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("age")]
        public int Age { get; set; }
        [Required]
        [Column("address")]
        [StringLength(100)]
        public string Address { get; set; }
        [Column("deptID")]
        public int? DeptId { get; set; }
        [Column("userID")]
        public int? UserId { get; set; }

        [ForeignKey(nameof(DeptId))]
        [InverseProperty(nameof(Department.Student))]
        public virtual Department Dept { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Users.Student))]
        public virtual Users User { get; set; }
        [InverseProperty("Student")]
        public virtual ICollection<StudentAnswers> StudentAnswers { get; set; }
        [InverseProperty("Student")]
        public virtual ICollection<StudentCourse> StudentCourse { get; set; }
    }
}