// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class Topic
    {
        [Key]
        [Column("topicID")]
        public int TopicId { get; set; }
        [Required]
        [Column("topicName")]
        [StringLength(50)]
        public string TopicName { get; set; }
        [Column("courseID")]
        public int? CourseId { get; set; }

        [ForeignKey(nameof(CourseId))]
        [InverseProperty("Topic")]
        public virtual Course Course { get; set; }
    }
}