// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class Topic
    {
        public int topicID { get; set; }
        public string topicName { get; set; }
        public int? courseID { get; set; }

        public virtual Course course { get; set; }
    }
}