// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ExamSystem.Entities
{
    public partial class User
    {
        public User()
        {
            Instructors = new HashSet<Instructor>();
            Students = new HashSet<Student>();
        }

        public string username { get; set; }
        public string password { get; set; }
        public string type { get; set; }
        public int userID { get; set; }

        public virtual ICollection<Instructor> Instructors { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}